# Generated by Django 4.2 on 2025-09-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('oneplus', 'OnePlus'), ('huawei', 'Huawei'), ('oppo', 'OPPO'), ('vivo', 'Vivo'), ('realme', 'Realme'), ('nokia', 'Nokia'), ('motorola', 'Motorola'), ('other', 'Other')], max_length=50)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('storage_capacity', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='in_stock', max_length=20)),
                ('main_image', models.ImageField(help_text='Main product image', upload_to='inventory/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('screen_size', models.CharField(blank=True, max_length=20)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=20)),
                ('camera_main', models.CharField(blank=True, max_length=50)),
                ('battery_capacity', models.CharField(blank=True, max_length=20)),
                ('operating_system', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Key features separated by commas')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'Inventory',
                'ordering': ['-created_at'],
            },
        ),
    ]
