# Generated by Django 4.2 on 2025-09-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.inventory'),
        ),
    ]
